/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.view;

/**
 *
 * @author Vítor
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        sairdo = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        produtoCadastro = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        produtoRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mega Estoque");

        menuHome.setText("Inicio");

        home.setText("Inicio");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menuHome.add(home);

        sairdo.setText("Sair");
        sairdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairdoActionPerformed(evt);
            }
        });
        menuHome.add(sairdo);

        menuBar.add(menuHome);

        menuProdutos.setText("Produtos");

        produtoCadastro.setText("Cadastro Produtos");
        produtoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoCadastroMouseClicked(evt);
            }
        });
        produtoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoCadastroActionPerformed(evt);
            }
        });
        menuProdutos.add(produtoCadastro);

        menuBar.add(menuProdutos);

        menuRelatorio.setText("Relatorio");

        produtoRelatorio.setText("Relario Protudos");
        produtoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoRelatorioActionPerformed(evt);
            }
        });
        menuRelatorio.add(produtoRelatorio);

        menuBar.add(menuRelatorio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

    }//GEN-LAST:event_homeMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void sairdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairdoActionPerformed
        new LoginUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_sairdoActionPerformed

    private void produtoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoCadastroMouseClicked

    }//GEN-LAST:event_produtoCadastroMouseClicked

    private void produtoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoCadastroActionPerformed
        new CadastroProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoCadastroActionPerformed

    private void produtoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoRelatorioActionPerformed
        new RelatorioProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem home;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem produtoCadastro;
    private javax.swing.JMenuItem produtoRelatorio;
    private javax.swing.JMenuItem sairdo;
    // End of variables declaration//GEN-END:variables
}
