/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.estoque.view;

import br.com.estoque.dao.ProdutoDao;
import br.com.estoque.dao.ProdutoDaoImpl;
import br.com.estoque.model.ProdutoEstoque;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vítor
 */
public class RelatorioProdutos extends javax.swing.JFrame {
    private ProdutoDao produtoDao = new ProdutoDaoImpl();
    private List<ProdutoEstoque> produtosEstoques;
    private DefaultTableModel tabelaModelo;
    
    /**
     * Creates new form RelatorioProdutos
     */
    public RelatorioProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        lbProduto = new javax.swing.JLabel();
        varProduto = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        varTabela = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        home = new javax.swing.JMenuItem();
        sairdo = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        produtoCadastro = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        produtoRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 367));

        jPanel1.setPreferredSize(new java.awt.Dimension(650, 367));

        titulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Relatório Produto Mega Estoque");

        lbProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbProduto.setText("Produto:");

        varProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varProdutoActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        varTabela.setAutoCreateRowSorter(true);
        varTabela.setBackground(new java.awt.Color(255, 255, 255));
        varTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProduto", "Produto", "Quantidade", "Preço", "Código de Barras"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(varTabela);
        if (varTabela.getColumnModel().getColumnCount() > 0) {
            varTabela.getColumnModel().getColumn(0).setResizable(false);
            varTabela.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(lbProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(varProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btPesquisar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto)
                    .addComponent(varProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        menuHome.setText("Inicio");

        home.setText("Inicio");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        menuHome.add(home);

        sairdo.setText("Sair");
        sairdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairdoActionPerformed(evt);
            }
        });
        menuHome.add(sairdo);

        menuBar.add(menuHome);

        menuProdutos.setText("Produtos");

        produtoCadastro.setText("Cadastro Produtos");
        produtoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtoCadastroMouseClicked(evt);
            }
        });
        produtoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoCadastroActionPerformed(evt);
            }
        });
        menuProdutos.add(produtoCadastro);

        menuBar.add(menuProdutos);

        menuRelatorio.setText("Relatorio");
        menuRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioActionPerformed(evt);
            }
        });

        produtoRelatorio.setText("Relario Protudos");
        produtoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoRelatorioActionPerformed(evt);
            }
        });
        menuRelatorio.add(produtoRelatorio);

        menuBar.add(menuRelatorio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

    }//GEN-LAST:event_homeMouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        new Principal().setVisible(true);
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void sairdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairdoActionPerformed
        new LoginUsuario().setVisible(true);
        dispose();
    }//GEN-LAST:event_sairdoActionPerformed

    private void produtoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtoCadastroMouseClicked

    }//GEN-LAST:event_produtoCadastroMouseClicked

    private void produtoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoCadastroActionPerformed
        new CadastroProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoCadastroActionPerformed

    private void varProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varProdutoActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String nome = varProduto.getText().trim();
        try {
            if(nome.length() >= 1){
                produtosEstoques = produtoDao.pesquisarPorNome(nome);
                popularTabela(produtosEstoques);
            }else{
                produtosEstoques = produtoDao.pesquisarPorNome(nome);
                popularTabela(produtosEstoques);
            }
            
            
        } catch (Exception e) {
            System.out.println("Erro ao pesquisar produto" + e.getMessage());
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void produtoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoRelatorioActionPerformed
        new RelatorioProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoRelatorioActionPerformed

    private void menuRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioActionPerformed
        new RelatorioProdutos().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuRelatorioActionPerformed

    public void popularTabela(List<ProdutoEstoque> produtos){
        tabelaModelo = (DefaultTableModel) varTabela.getModel();
        // Limpando a tabelaModelo
        tabelaModelo.setNumRows(0);
        for (ProdutoEstoque produto : produtos) {
            tabelaModelo.addRow(new Object[]{produto.getIdProduto(), produto.getNomeProduto(), produto.getUnidadeEmEstoque(), produto.getPrecoUnitario(), produto.getCodigoBarra()});
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JMenuItem home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem produtoCadastro;
    private javax.swing.JMenuItem produtoRelatorio;
    private javax.swing.JMenuItem sairdo;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField varProduto;
    private javax.swing.JTable varTabela;
    // End of variables declaration//GEN-END:variables
}
